# Generated by Django 3.1.5 on 2021-01-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='release_date',
            field=models.CharField(max_length=30, unique_for_date=models.CharField(max_length=30, verbose_name='Название'), verbose_name='Дата'),
        ),
    ]
