# Generated by Django 3.1.5 on 2021-01-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210115_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
