# Generated by Django 3.1.5 on 2021-01-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210119_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='color',
        ),
        migrations.RemoveField(
            model_name='task',
            name='details',
        ),
        migrations.RemoveField(
            model_name='task',
            name='not_ful_box',
        ),
        migrations.RemoveField(
            model_name='task',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='adjustments',
            field=models.CharField(blank=True, max_length=10, verbose_name='Дельта'),
        ),
        migrations.AddField(
            model_name='task',
            name='after_adjustment_delta',
            field=models.CharField(blank=True, max_length=10, verbose_name='Дельта'),
        ),
        migrations.AddField(
            model_name='task',
            name='after_adjustment_quantity_1c',
            field=models.CharField(blank=True, max_length=10, verbose_name='Дельта'),
        ),
        migrations.AddField(
            model_name='task',
            name='after_adjustment_quantity_actual',
            field=models.CharField(blank=True, max_length=10, verbose_name='Дельта'),
        ),
        migrations.AddField(
            model_name='task',
            name='code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Дельта'),
        ),
        migrations.AddField(
            model_name='task',
            name='color_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Дельта'),
        ),
        migrations.AddField(
            model_name='task',
            name='delta',
            field=models.CharField(blank=True, max_length=10, verbose_name='Дельта'),
        ),
        migrations.AddField(
            model_name='task',
            name='details_name',
            field=models.CharField(blank=True, max_length=10, verbose_name='Дельта'),
        ),
        migrations.AddField(
            model_name='task',
            name='quantity_1c',
            field=models.CharField(blank=True, max_length=10, verbose_name='Дельта'),
        ),
        migrations.AddField(
            model_name='task',
            name='quantity_actual',
            field=models.CharField(blank=True, max_length=10, verbose_name='Дельта'),
        ),
    ]
