# Generated by Django 3.1.5 on 2021-01-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210119_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Код детали'),
        ),
        migrations.AlterField(
            model_name='task',
            name='details_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Дельта'),
        ),
    ]
