# Generated by Django 3.1.5 on 2021-01-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210120_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='adjustments_marriage',
            field=models.CharField(blank=True, max_length=10, verbose_name='Списание в брак'),
        ),
        migrations.AlterField(
            model_name='task',
            name='adjustments_marriage',
            field=models.CharField(blank=True, max_length=10, verbose_name='Списание в брак'),
        ),
    ]
