# Generated by Django 3.1.5 on 2021-01-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210120_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessories',
            options={'ordering': ['-release_date'], 'verbose_name': 'Данные комплектующих', 'verbose_name_plural': 'Данные комплектующих'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-release_date'], 'verbose_name': 'Данные полуфабриката', 'verbose_name_plural': 'Данные полуфабриката'},
        ),
    ]
