# Generated by Django 3.1.5 on 2021-01-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.TextField(max_length=30, verbose_name='Код цвета'),
        ),
    ]
