# Generated by Django 3.1.5 on 2021-01-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210115_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='release_date',
            field=models.DateField(auto_now=True),
        ),
    ]
