# Generated by Django 3.1.5 on 2021-01-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210115_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='details',
            field=models.CharField(blank=True, max_length=10, verbose_name='Количество штук'),
        ),
        migrations.AddField(
            model_name='task',
            name='not_ful_box',
            field=models.CharField(blank=True, max_length=10, verbose_name='Не полные сьемы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='quantity',
            field=models.CharField(blank=True, max_length=8, verbose_name='Количество коробок'),
        ),
    ]
