# Generated by Django 3.1.5 on 2021-01-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210115_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.IntegerField(blank=True, max_length=10, verbose_name='Количество штук'),
        ),
    ]
