# Generated by Django 3.1.5 on 2021-01-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210117_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['release_date'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True, max_length=30, verbose_name='Количество штук'),
        ),
    ]
