# Generated by Django 3.1.5 on 2021-01-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210119_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_name', models.CharField(blank=True, max_length=100, verbose_name='Дельта')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Код детали')),
                ('quantity_actual', models.CharField(blank=True, max_length=10, verbose_name='Фактический остаток')),
                ('quantity_1c', models.CharField(blank=True, max_length=10, verbose_name='Остаток 1с')),
                ('delta', models.CharField(blank=True, max_length=10, verbose_name='Дельта')),
                ('adjustments', models.CharField(blank=True, max_length=10, verbose_name='Корректировка')),
                ('adjustments_marriage', models.CharField(blank=True, max_length=10, verbose_name='Корректировка')),
                ('after_adjustment_quantity_actual', models.CharField(blank=True, max_length=10, verbose_name='Фактический остаток после корректировки')),
                ('after_adjustment_quantity_1c', models.CharField(blank=True, max_length=10, verbose_name='Остаток 1с после корректировки')),
                ('after_adjustment_delta', models.CharField(blank=True, max_length=10, verbose_name='Дельта после корректировки')),
                ('release_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-release_date'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='adjustments_marriage',
            field=models.CharField(blank=True, max_length=10, verbose_name='Корректировка'),
        ),
    ]
