# Generated by Django 3.1.5 on 2021-01-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210120_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='release_date',
            field=models.CharField(max_length=20, verbose_name='Дата пересчета'),
        ),
        migrations.AlterField(
            model_name='task',
            name='release_date',
            field=models.CharField(max_length=20, verbose_name='Дата пересчета'),
        ),
    ]
