# Generated by Django 3.1.5 on 2021-01-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210126_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='release_date',
            field=models.CharField(max_length=20, verbose_name='Дата пересчета'),
        ),
    ]
