# Generated by Django 3.1.5 on 2021-01-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210126_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='release_date',
            field=models.DateField(verbose_name='Дата пересчета'),
        ),
    ]
