# Generated by Django 3.1.5 on 2021-01-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210126_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='release_date',
            field=models.DateField(blank=True, verbose_name='Дата пересчета'),
        ),
    ]
