# Generated by Django 3.1.5 on 2021-01-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210127_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='release_date',
            field=models.CharField(blank=True, max_length=20, verbose_name='Дата пересчета'),
        ),
    ]
