# Generated by Django 3.1.5 on 2021-02-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210127_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='release_date',
            field=models.DateField(verbose_name='Дата пересчета'),
        ),
        migrations.AlterField(
            model_name='task',
            name='release_date',
            field=models.DateField(verbose_name='Дата пересчета'),
        ),
    ]
