# Generated by Django 3.1.5 on 2021-02-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210202_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='actual_registration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Постановка на учет'),
        ),
        migrations.AddField(
            model_name='task',
            name='actual_registration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Постановка на учет'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='adjustments',
            field=models.CharField(blank=True, max_length=50, verbose_name='Корректировка'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='adjustments_marriage',
            field=models.CharField(blank=True, max_length=50, verbose_name='Списание в брак'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='after_adjustment_delta',
            field=models.CharField(blank=True, max_length=50, verbose_name='Дельта после корректировки'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='after_adjustment_quantity_1c',
            field=models.CharField(blank=True, max_length=50, verbose_name='Остаток 1с после корректировки'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='after_adjustment_quantity_actual',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фактический остаток после корректировки'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Код детали'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='delta',
            field=models.CharField(blank=True, max_length=50, verbose_name='Дельта'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='quantity_1c',
            field=models.CharField(blank=True, max_length=50, verbose_name='Остаток 1с'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='quantity_actual',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фактический остаток'),
        ),
        migrations.AlterField(
            model_name='task',
            name='adjustments',
            field=models.CharField(blank=True, max_length=50, verbose_name='Корректировка'),
        ),
        migrations.AlterField(
            model_name='task',
            name='adjustments_marriage',
            field=models.CharField(blank=True, max_length=50, verbose_name='Списание в брак'),
        ),
        migrations.AlterField(
            model_name='task',
            name='after_adjustment_delta',
            field=models.CharField(blank=True, max_length=50, verbose_name='Дельта после корректировки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='after_adjustment_quantity_1c',
            field=models.CharField(blank=True, max_length=50, verbose_name='Остаток 1с после корректировки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='after_adjustment_quantity_actual',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фактический остаток после корректировки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Код детали'),
        ),
        migrations.AlterField(
            model_name='task',
            name='color_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Код цвета'),
        ),
        migrations.AlterField(
            model_name='task',
            name='delta',
            field=models.CharField(blank=True, max_length=50, verbose_name='Дельта'),
        ),
        migrations.AlterField(
            model_name='task',
            name='quantity_1c',
            field=models.CharField(blank=True, max_length=50, verbose_name='Остаток 1с'),
        ),
        migrations.AlterField(
            model_name='task',
            name='quantity_actual',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фактический остаток'),
        ),
    ]
